Studentinfo/Models/Domain/Student.cs
namespace Studentinfo.Models.Domain
{
    public class Student
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public string? Department { get; set; }
        public string? Session {  get; set; }
    }
}

Studentinfo/Models/ErrorViewModel.cs
namespace Studentinfo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Studentinfo/Models/ViewModel/AddStudentRequest.cs
namespace Studentinfo.Models.ViewModel
{
    public class AddStudentRequest
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public string? Department { get; set; }
        public string? Session { get; set; }
    }
}

Studentinfo/Models/ViewModel/EditStudentRequest.cs
namespace Studentinfo.Models.ViewModel
{
    public class EditStudentRequest
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public string? Department { get; set; }
        public string? Session { get; set; }
    }
}

Studentinfo/Controllers/AdminStudentController.cs
using Microsoft.AspNetCore.Mvc;
using Studentinfo.Data;
using Studentinfo.Models.ViewModel;
using Studentinfo.Models.Domain;

namespace Studentinfo.Controllers
{
    public class AdminStudentController : Controller
    {
        private readonly StudentDbcontext studentDbcontext;

        public AdminStudentController(StudentDbcontext studentDbcontext)
        {
            this.studentDbcontext = studentDbcontext;
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(AddStudentRequest addStudentRequest)
        {
            var student = new Student
            {
                Name = addStudentRequest.Name,
                Department = addStudentRequest.Department,
                Session = addStudentRequest.Session
            };

            studentDbcontext.Students.Add(student);
            studentDbcontext.SaveChanges();

            return RedirectToAction("List");
        }

        [HttpGet]
        public IActionResult List() {
            var students=studentDbcontext.Students.ToList();
            return View(students);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var student = studentDbcontext.Students.FirstOrDefault(x => x.Id == id);
            if (student != null)
            {
                var editStudentRequest = new EditStudentRequest
                {
                    Id = student.Id,
                    Name = student.Name,
                    Department = student.Department,
                    Session = student.Session
                };
                return View(editStudentRequest);
            }
            return View(null);
        }

        [HttpPost]
        public IActionResult Edit(EditStudentRequest editStudentRequest)
        {
            var student = new Student
            {
                Id=editStudentRequest.Id,
                Name = editStudentRequest.Name,
                Department = editStudentRequest.Department,
                Session = editStudentRequest.Session
            };
            var existingStudent=studentDbcontext.Students.Find(student.Id);
            if (existingStudent != null) 
            { 
            existingStudent.Name = student.Name;
                existingStudent.Department = student.Department;
                existingStudent.Session = student.Session;
                studentDbcontext.SaveChanges();
            }
            return RedirectToAction("List");
        }

        [HttpPost]
        public IActionResult Delete(EditStudentRequest editStudentRequest) { 
            var student=studentDbcontext.Students.Find(editStudentRequest.Id);
            if (student != null)
            {
                studentDbcontext.Students.Remove(student);
                studentDbcontext.SaveChanges();
            }
            return RedirectToAction("List");
        }
    }
}

Studentinfo/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Studentinfo.Models;

namespace Studentinfo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Studentinfo/Views/AdminStudent/Add.cshtml
@model Studentinfo.Models.ViewModel.AddStudentRequest
@{
}
<div class="bg-secondary bg-opacity-10 py-2">
	<div class="container">
		<h1>Add new student</h1>
	</div>

    <div class="container py-5">
    <form method="post">
        <div class="form-group mb-3">
            <label for="Name">Name</label>
                <input type="text" class="form-control" id="name" placeholder="Enter your name" asp-for="Name" />
        </div>
        <div class="form-group mb-3">
            <label for="Department">Department</label>
                <input type="text" class="form-control" id="department" placeholder="Department" asp-for="Department" />
        </div>
            <div class="form-group mb-3">
                <label for="Session">Session</label>
                <input type="text" class="form-control" id="session" placeholder="Session" asp-for="Session" />
            </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    </div>
</div>

Studentinfo/Views/AdminStudent/Edit.cshtml
@model Studentinfo.Models.ViewModel.EditStudentRequest
@{
}
<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1>Edit student info</h1>
    </div>

    <div class="container py-5">
        <form method="post">
            <div class="form-group mb-3">
                <label for="Id">Id</label>
                <input type="text" class="form-control" id="id" asp-for="Id" readonly/>
            </div>
            <div class="form-group mb-3">
                <label for="Name">Name</label>
                <input type="text" class="form-control" id="name" asp-for="Name" />
            </div>
            <div class="form-group mb-3">
                <label for="Department">Department</label>
                <input type="text" class="form-control" id="department" asp-for="Department" />
            </div>
            <div class="form-group mb-3">
                <label for="Session">Session</label>
                <input type="text" class="form-control" id="session" asp-for="Session" />
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
            <button type="submit" class="btn btn-outline-success" asp-controller="AdminStudent" asp-action="Delete">Delete</button>
        </form>
    </div>
</div>

Studentinfo/Views/AdminStudent/List.cshtml
@model List<Studentinfo.Models.Domain.Student>

@{
}
<div class="bg-secondary bg-opacity-10 py-2">
	<div class="container">
		<h1>Show All Students</h1>
	</div>
</div>

<div class="container py-5">
    @if(Model!=null && Model.Any()){
        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Department</th>
                    <th>Session</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var student in Model)
                {
                    <tr>
                        <td>@student.Id</td>
                        <td>@student.Name</td>
                        <td>@student.Department</td>
                        <td>@student.Session</td>
                        <td><a asp-controller="AdminStudent" asp-action="Edit" asp-route-Id="@student.Id">Edit</a></td>
                    </tr>
                }

            </tbody>
        </table>
	}
    else{
        <p>No Data Found.</p>
    }
</div>

Studentinfo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Studentinfo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Studentinfo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Studentinfo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Studentinfo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Student
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="AdminStudent" asp-action="Add">Add Student</a>
                                <a class="dropdown-item" asp-area="" asp-controller="AdminStudent" asp-action="List">View Students</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Studentinfo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>